# Generated by Django 2.2.3 on 2019-08-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('age', models.IntegerField(max_length=128)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=12)),
                ('extra', models.TextField()),
            ],
        ),
    ]
