# Generated by Django 2.2.3 on 2019-08-09 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empinfo',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(128)]),
        ),
    ]
