# Generated by Django 2.2.3 on 2019-08-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapi', '0002_companyinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyList',
        ),
    ]
