# Generated by Django 2.2.3 on 2019-08-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapi', '0003_delete_companylist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyInfo',
            new_name='CompanyList',
        ),
    ]
