# Generated by Django 2.2.3 on 2019-08-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapi', '0004_auto_20190809_1821'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='empinfo',
            constraint=models.UniqueConstraint(fields=('username',), name='username_unique'),
        ),
    ]
